# Generated by Django 5.2.1 on 2025-05-22 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='video',
            name='teacher',
        ),
    ]
