# Generated by Django 5.2.1 on 2025-05-22 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_remove_note_teacher_remove_video_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='embed_code',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.URLField(blank=True),
        ),
    ]
