# Generated by Django 5.2.1 on 2025-05-22 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_course_alter_article_content_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacher',
            old_name='social_link',
            new_name='facebook',
        ),
        migrations.AddField(
            model_name='teacher',
            name='address',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='teacher',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='teacher',
            name='twitter',
            field=models.URLField(blank=True),
        ),
    ]
