# Generated by Django 5.2.1 on 2025-05-22 18:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_rename_social_link_teacher_facebook_teacher_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.subject'),
        ),
    ]
