# Generated by Django 5.2.1 on 2025-05-22 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_alter_video_subject'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfbook',
            name='teacher',
        ),
        migrations.AddField(
            model_name='note',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
        migrations.AddField(
            model_name='pdfbook',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='notes/'),
        ),
    ]
