# Generated by Django 5.2.1 on 2025-05-22 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0007_remove_pdfbook_teacher_note_cover_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pdfbook',
            name='cover_image',
        ),
        migrations.AddField(
            model_name='pdfbook',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='profiles.teacher'),
            preserve_default=False,
        ),
    ]
