# Generated by Django 5.2.1 on 2025-05-23 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_remove_pdfbook_teacher_pdfbook_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='subjects',
        ),
    ]
