# Generated by Django 5.2.1 on 2025-05-23 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_remove_teacher_subjects'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfbook',
            name='content',
            field=models.TextField(default='Sameer'),
            preserve_default=False,
        ),
    ]
