# Generated by Django 5.2.1 on 2025-05-23 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0012_pdfbook_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='contactmessage',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='meetuprequest',
            name='teacher',
        ),
        migrations.RemoveField(
            model_name='review',
            name='teacher',
        ),
    ]
