# Generated by Django 5.2.1 on 2025-05-23 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0013_remove_availability_teacher_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image', models.ImageField(upload_to='gallery/')),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('program', 'Program'), ('event', 'Event'), ('education', 'Education'), ('cultural', 'Cultural'), ('social', 'Social'), ('training', 'Training'), ('seminar', 'Seminar'), ('workshop', 'Workshop'), ('sports', 'Sports'), ('other', 'Other')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
