# Generated by Django 5.2.1 on 2025-05-23 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0014_gallery'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallery',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='category',
            field=models.CharField(choices=[('program', 'Program'), ('event', 'Event'), ('education', 'Education'), ('achievement', 'Achievement'), ('training', 'Training'), ('workshop', 'Workshop'), ('seminar', 'Seminar'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
