app = "your-app-name"         # must be unique
primary_region = "ams"        # or other region close to you

[build]
  dockerfile = "Dockerfile"

[env]
  DEBUG = "False"
  ALLOWED_HOSTS = "narayan.fly.dev"

[[services]]
  internal_port = 8000
  protocol = "tcp"

  [[services.ports]]
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443
